name: Rebuild and Push Sonarr/Radarr

on:
  schedule:
    - cron: "0 0 * * 1"   # Runs every Monday at midnight UTC
  workflow_dispatch:       # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Sonarr
        run: |
          docker build --pull -t ghcr.io/${{ github.repository_owner }}/sonarr-custom:latest ./sonarr
          docker push ghcr.io/${{ github.repository_owner }}/sonarr-custom:latest

      - name: Build and push Radarr
        run: |
          docker build --pull -t ghcr.io/${{ github.repository_owner }}/radarr-custom:latest ./radarr
          docker push ghcr.io/${{ github.repository_owner }}/radarr-custom:latest
